# action.yml
name: 'aptly action'
description: 'publish with aptly to minio'
inputs:
  aws-id:
    description: 'id for publish aptly'
    required: true
  aws-secret:
    description: 'secret for aws'
    required: true
  gpg-key:
    description: 'gpg key for debian repo'
    required: true
  repo-name:  # id of input
    description: 'repository name of pushing'
    required: true
  build-version:
    description: 'build version'
    required: true
    default: 1.0.0
runs:
  using: 'docker'
  image: 'docker://ewadocker90/aptly:aptly'
  env:
     AWS_ACCESS_KEY_ID: ${{ inputs.aws-id }}
     AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret }}
     BUILD_VERSION: ${{ inputs.build-version }}
     REPO_NAME: ${{ inputs.repo-name }}
  args:
    - "-f"
    - ${{ inputs.gpg-key }}
    - ./aptly.sh
  pre-entrypoint: '/home/github/entrypoint.sh'
  entrypoint: '/home/github/aptly.sh'
