name: Aptly docker image generation
on:
  push:
    branches:
      - master
      - feature/*

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v2

  build:
    runs-on: self-hosted
    needs: checkout

    steps:
      - name: build image
        run: |
          docker build \
            -t ghcr.io/ERWEKA/aptly:1.1.0 \
            .

      - name: push to registry
        run: |
          echo ${{ secrets.REGISTRY_DOCKER_GITHUB }} | docker login ghcr.io -u erweka --password-stdin
          docker push ghcr.io/ERWEKA/aptly:1.1.0